<script setup>
import { ArrowRight, ArrowDown, Gavel, Repeat2, Combine, Sprout, Vault } from 'lucide-vue-next'
import PayoffExplorer from './PayoffExplorer.vue'
import MarketTable from './MarketTable.vue'
import { concepts } from '../concepts.js'
const emit = defineEmits(['navigate'])
const steps = [{ icon: Vault, text: 'Deposit Stock Token' }, { icon: Sprout, text: 'Split Income + Upside' }, { icon: Gavel, text: 'Auction Upside' }, { icon: Repeat2, text: 'Trade the epoch' }, { icon: Combine, text: 'Settle or recompose' }]
const features = [{ title: 'Open listing rules', description: 'Any Stock Token with a Chainlink feed and a USDG pool can qualify; the factory owner registers it directly, with no delay at launch.' }, { title: 'Earn income', description: 'Hold Income: the Stock Token up to the cap, plus the auction premium.' }, { title: 'Access upside', description: 'Hold Upside: the move above the cap price, prefunded by the vault. No borrowing.' }, { title: 'Recompose', description: 'Merge Income + Upside back into the Stock Token. Any time, no fee.' }]
</script>

<template>
  <section class="hero section-border"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Onchain markets · Robinhood Chain</p><h1 tabindex="-1">Trade the<br />market you see.</h1><p class="hero-subtitle">Split exposure. Keep control.</p><p class="hero-description">Deposit a Stock Token and open two transparent positions: Income for the defined range, Upside for the move above it. Review every quote before you connect.</p><div class="actions"><a href="/app/markets" class="button primary" @click.prevent="emit('navigate','/app/markets')">Open markets <ArrowRight :size="16" /></a><a href="/app/markets" class="button" @click.prevent="emit('navigate','/app/markets')">View watchlist</a></div><div class="hero-status"><span class="status-dot"></span><span>Robinhood Chain</span><span class="status-divider"></span><span>Model quotes</span></div></div><div class="hero-visual"><div class="hero-image"><img src="/hero.webp" alt="Abstract market dashboard with a neon token and live signal line" width="2000" height="1125" fetchpriority="high" /></div><a href="#split" class="subtle-link">See the split <ArrowDown :size="16" /></a></div></div></section>
  <section id="split" class="section-border"><div class="container section-space split-grid"><div class="section-copy"><p class="section-kicker">01 / position builder</p><h2>Split<br />your exposure.</h2><p class="section-lead">One Stock Token becomes two tradable positions.</p><p class="body-small">Deposit a Stock Token (e.g. AAPL). The vault issues Income and Upside at the cap you choose, so you can express a view without hidden leverage.</p><a href="#the-mechanism" class="text-link">How the split works <ArrowRight :size="14" /></a></div><div class="split-visual"><p class="eyebrow">Example: AAPL at $250</p><div class="split-diagram"><div class="asset-card"><span class="apple-token">A</span><div><b>AAPL</b><span class="mono">$250.00</span></div></div><ArrowRight class="split-arrow" :size="20" /><div class="position-card income-card"><p class="eyebrow"><span class="split-mark"></span> Income</p><div><strong>$247.29</strong><span>Up to the cap</span></div></div><div class="position-card upside-card"><p class="eyebrow"><span class="upside-mark">↗</span> Upside</p><div><strong>$2.71</strong><span>Above the cap</span></div></div></div><p class="split-caption">Cap: +5% <span>·</span> Cap price (K): $262.50</p><p class="model-caption">Indicative model · the auction sets the price</p><div class="split-image"><img src="/stack.webp" alt="Layered onchain position cards showing the market split" width="1200" height="1200" loading="lazy" /></div></div></div></section>
  <PayoffExplorer />
  <section id="income" class="income-band section-border"><img class="band-image" src="/talis/bg-income-position.webp" alt="" width="1672" height="941" loading="lazy" /><div class="band-overlay"></div><div class="container band-space"><div class="band-copy"><p class="eyebrow"><span class="split-mark"></span> Income position</p><h2>Keep the asset.<br />Earn the premium.</h2><p>Accept an upside cap for a defined period.<br />Receive the premium paid by the upside buyer.</p><p class="accent-note">Underlying downside exposure remains.</p><div class="actions"><a href="/app/markets" class="button dark-outline small" @click.prevent="emit('navigate','/app/markets')">Markets <ArrowRight :size="14" /></a><a href="/docs#concept-income-position" class="text-link" @click.prevent="emit('navigate','/docs#concept-income-position')">How income positions settle</a></div></div></div></section>
  <section id="upside" class="section-border"><div class="container band-space upside-grid"><div class="band-copy"><p class="eyebrow"><span class="upside-mark">↗</span> Upside position</p><h2>Buy the move<br />above the cap.</h2><p>Pay a premium for exposure above a defined level.<br />The position can expire without a payoff.</p><p class="accent-note green-text">Concentrated upside exposure.</p><div class="actions"><a href="/app/auctions" class="button lime small" @click.prevent="emit('navigate','/app/auctions')">Auctions <ArrowRight :size="14" /></a><a href="/docs#concept-upside-position" class="text-link" @click.prevent="emit('navigate','/docs#concept-upside-position')">How upside positions settle</a></div></div><div class="upside-image"><img src="/talis/flyer-upside-position.webp" alt="A lime stone wedge rising from left to right: the move above the cap" width="1600" height="900" loading="lazy" /></div></div></section>
  <section id="the-mechanism" class="mechanism-band section-border"><img class="band-image" src="/network.webp" alt="" width="1200" height="1200" loading="lazy" /><div class="band-overlay"></div><div class="container section-space mechanism-grid"><div class="section-copy"><p class="section-kicker">02 / settlement rail</p><h2>Real collateral.<br />No forced close.</h2><p class="section-lead">The vault holds the Stock Token.</p><p class="body-small">Upside is prefunded by that Stock Token: no borrowing, no funding rate, no liquidation engine. Both positions are plain ERC-20s on Robinhood Chain.</p><a href="/docs#mechanism" class="text-link" @click.prevent="emit('navigate','/docs#mechanism')">Read the mechanism <ArrowRight :size="14" /></a></div><ol class="mechanism-steps"><li v-for="(step,i) in steps" :key="step.text"><div class="step-icon"><component :is="step.icon" :size="21" /></div><p>{{ step.text }}</p><ArrowRight v-if="i < steps.length - 1" class="step-arrow" :size="15" /></li></ol></div></section>
  <section id="markets" class="section-border"><div class="container section-space"><div class="section-heading"><h2 class="compact-title">Live markets</h2><p class="body-small">One series per Stock Token, epoch and cap.</p></div><MarketTable compact @navigate="to => emit('navigate',to)" /><div class="section-heading market-foot"><a href="/app/markets" class="text-link green-text" @click.prevent="emit('navigate','/app/markets')">View all markets <ArrowRight :size="14" /></a><p class="model-caption">Illustrative market preview · no live price feed</p></div></div></section>
  <section id="how-it-works" class="section-border"><div class="container section-space"><div class="section-heading"><div><h2 class="compact-title">How it works</h2><p class="body-small concepts-intro">Fifteen concepts, one card each. Every card opens the detail in the docs.</p></div><a href="/docs#concepts" class="text-link green-text" @click.prevent="emit('navigate','/docs#concepts')">All concepts <ArrowRight :size="14" /></a></div><ul class="concept-carousel" aria-label="Concept flyers"><li v-for="(concept,i) in concepts" :key="concept.id"><a :href="`/docs#concept-${concept.id}`" @click.prevent="emit('navigate',`/docs#concept-${concept.id}`)"><img :src="concept.image" :alt="concept.title" width="1600" height="900" loading="lazy" /><p class="concept-title"><span class="mono">{{ String(i+1).padStart(2,'0') }}</span>{{ concept.title }}</p><p class="concept-description">{{ concept.description }}</p></a></li></ul></div></section>
  <section id="recompose" class="section-border"><div class="container section-space recompose-grid"><div class="recompose-image"><img src="/token.webp" alt="A market token with a signal line" width="2000" height="1125" loading="lazy" /></div><div class="band-copy"><p class="eyebrow"><span class="paired-mark"><i></i><i></i></span> Recompose</p><h2>Separate.<br />Recombine.</h2><p>One Income position plus one Upside position of the same series merge back into one Stock Token.</p><p class="body-small">Any time during the epoch, no fee. Income + Upside is the whole unit; either half can be held or sold on its own.</p><div class="actions"><a href="/app/recompose" class="button primary small" @click.prevent="emit('navigate','/app/recompose')">Recompose <ArrowRight :size="14" /></a><a href="/docs#concept-position-redemption" class="text-link" @click.prevent="emit('navigate','/docs#concept-position-redemption')">Position redemption</a></div></div></div></section>
  <section><div class="container section-space"><ul class="feature-grid"><li v-for="(item,i) in features" :key="item.title"><span class="feature-icon">{{ String(i+1).padStart(2,'0') }}</span><div><h3 class="eyebrow">{{ item.title }}</h3><p>{{ item.description }}</p><a v-if="i===0" href="/app/launchpad" class="text-link green-text" @click.prevent="emit('navigate','/app/launchpad')">Propose a market <ArrowRight :size="12" /></a></div></li></ul></div></section>
</template>
