<script setup>
import { ArrowRight, ArrowUpRight, Search, SlidersHorizontal } from 'lucide-vue-next'
import { ref, computed } from 'vue'
import MarketTable from './MarketTable.vue'
const props = defineProps({ path: { type: String, default: '/app/markets' } })
const emit = defineEmits(['navigate'])
const query = ref('')
const side = ref('All')
const showFilters = ref(false)
const pageTitle = computed(() => props.path.includes('launchpad') ? 'Launchpad' : props.path.includes('auctions') ? 'Auctions' : props.path.includes('recompose') ? 'Recompose positions' : 'Markets')
const copy = computed(() => ({ Markets: 'Browse Stock Token series with a defined cap. Prices are illustrative until a market data provider is connected.', Launchpad: 'Propose a Stock Token market. This interface records the shape of the request; no listing transaction is enabled.', Auctions: 'Explore Upside auctions. The sample series below explains the settlement model without placing an order.', 'Recompose positions': 'Merge one Income position and one Upside position from the same series back into one Stock Token.' }[pageTitle.value]))
</script>

<template>
  <section class="workspace container"><div class="workspace-head"><div><p class="eyebrow">Scenovia workspace · Robinhood Chain preview</p><h1 tabindex="-1">{{ pageTitle }}</h1><p class="workspace-lede">{{ copy }}</p></div><a href="/" class="text-link" @click.prevent="emit('navigate','/')">Back to markets <ArrowRight :size="14" /></a></div>
    <div v-if="pageTitle === 'Launchpad'" class="workspace-card launchpad-card"><div><p class="eyebrow">Open listing rules</p><h2>Suggest a market.</h2><p>Any Stock Token with a price feed and liquidity pool may qualify. Connect nothing here: this preview keeps the request local.</p></div><a href="/docs#listing" class="button primary" @click.prevent="emit('navigate','/docs#listing')">Read listing notes <ArrowUpRight :size="16" /></a></div>
    <div v-else-if="pageTitle === 'Recompose positions'" class="workspace-card recompose-panel"><p class="eyebrow">Income + Upside</p><h2>One asset again.</h2><p>Selecting and merging positions would require a wallet transaction. This local preview keeps wallet actions disabled.</p><button class="button" type="button" disabled>Recompose disabled in preview</button></div>
    <template v-else><div class="stats-strip"><div><span>Value locked</span><strong>—</strong></div><div><span>Premium received (net)</span><strong>—</strong></div><div><span>Epochs settled</span><strong>0</strong></div><div><span>Active series</span><strong>4</strong></div></div><div class="filters"><label class="search-field"><Search :size="15" /><span class="sr-only">Search markets</span><input v-model="query" placeholder="Search asset" /></label><div class="side-tabs"><button v-for="option in ['All','Income','Upside']" :key="option" :aria-pressed="side === option" :class="{active:side===option}" @click="side=option">{{ option }}</button></div><button class="filter-button" type="button" :aria-expanded="showFilters" @click="showFilters = !showFilters"><SlidersHorizontal :size="14" /> Market details</button></div><p v-if="showFilters" class="filter-details">All example series use a +5% cap, 30-day epoch and 25% model volatility.</p><MarketTable :query="query" :side="side" @reset="query = ''" @navigate="to => emit('navigate',to)" /></template>
  </section>
</template>

<style scoped>
.workspace{padding-block:76px 110px}.workspace-head{display:flex;align-items:flex-end;justify-content:space-between;gap:25px;border-bottom:1px solid var(--line);padding-bottom:40px}.workspace-head h1{margin:13px 0 12px;font-size:clamp(46px,5vw,68px);line-height:1;letter-spacing:-.06em;font-weight:600}.workspace-lede{max-width:570px;margin:0;color:var(--muted);font-size:14px;line-height:1.7}.stats-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;margin:32px 0;padding:24px;border:1px solid var(--line);border-radius:12px;background:var(--raised)}.stats-strip div{display:flex;flex-direction:column;gap:8px}.stats-strip span{font-family:var(--mono);font-size:10px;color:var(--muted)}.stats-strip strong{font:500 28px var(--mono);color:var(--green)}.filters{display:flex;align-items:center;gap:12px;margin:28px 0 16px}.search-field{display:flex;align-items:center;gap:8px;flex:1;max-width:320px;height:40px;padding:0 12px;border:1px solid var(--line);border-radius:999px;color:var(--muted)}.search-field input{width:100%;border:0;outline:0;background:none;color:var(--fg);font-size:12px}.side-tabs{display:flex;gap:4px}.side-tabs button,.filter-button{height:40px;padding:0 13px;border:1px solid var(--line);border-radius:999px;background:transparent;color:var(--muted);font-size:11px;cursor:pointer}.side-tabs button.active,.side-tabs button:hover{background:var(--green);border-color:var(--green);color:#fff}.filter-button{display:inline-flex;align-items:center;gap:6px;margin-left:auto}.workspace-card{display:flex;align-items:center;justify-content:space-between;gap:30px;margin-top:42px;padding:35px;border:1px solid var(--line);border-radius:12px;background:var(--raised)}.workspace-card h2{margin:12px 0;font-size:34px;letter-spacing:-.04em}.workspace-card p:not(.eyebrow){max-width:600px;margin:0;color:var(--muted);font-size:14px;line-height:1.7}.workspace-card button{margin-top:22px}.recompose-panel{display:block;max-width:780px}.launchpad-card{min-height:260px}@media(max-width:700px){.workspace{padding-block:50px 70px}.workspace-head{display:block}.workspace-head>.text-link{margin-top:24px}.stats-strip{grid-template-columns:1fr 1fr;gap:18px;padding:18px}.stats-strip strong{font-size:22px}.filters{flex-wrap:wrap}.search-field{max-width:none;flex-basis:100%}.filter-button{margin-left:0}.workspace-card{display:block;padding:24px}.workspace-card .button{margin-top:22px}}
</style>
